"Resource/UI/persistent_timer/persistent_timer_minutes.res"
{
    "PersistentTimerMinutesLabel0"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabel0"
        "xpos"			    "c-10"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "0"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerMinutesLabelShadow0"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabelShadow0"
        "xpos"			    "c-10"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "0"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerMinutesLabel1"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabel1"
        "xpos"			    "c-10"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "1"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerMinutesLabelShadow1"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabelShadow1"
        "xpos"			    "c-10"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "1"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerMinutesLabel2"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabel2"
        "xpos"			    "c-10"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "2"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerMinutesLabelShadow2"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabelShadow2"
        "xpos"			    "c-10"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "2"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerMinutesLabel3"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabel3"
        "xpos"			    "c-10"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "3"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerMinutesLabelShadow3"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabelShadow3"
        "xpos"			    "c-10"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "3"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerMinutesLabel4"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabel4"
        "xpos"			    "c-10"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "4"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerMinutesLabelShadow4"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabelShadow4"
        "xpos"			    "c-10"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "4"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerMinutesLabel5"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabel5"
        "xpos"			    "c-10"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "5"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerMinutesLabelShadow5"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabelShadow5"
        "xpos"			    "c-10"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "5"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerMinutesLabel6"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabel6"
        "xpos"			    "c-10"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "6"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerMinutesLabelShadow6"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabelShadow6"
        "xpos"			    "c-10"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "6"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerMinutesLabel7"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabel7"
        "xpos"			    "c-10"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "7"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerMinutesLabelShadow7"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabelShadow7"
        "xpos"			    "c-10"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "7"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerMinutesLabel8"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabel8"
        "xpos"			    "c-10"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "8"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerMinutesLabelShadow8"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabelShadow8"
        "xpos"			    "c-10"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "8"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerMinutesLabel9"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabel9"
        "xpos"			    "c-10"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "9"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerMinutesLabelShadow9"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerMinutesLabelShadow9"
        "xpos"			    "c-10"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "9"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }
}
