"Resource/UI/persistent_timer/persistent_timer_tens.res"
{
    "PersistentTimerTensLabel0"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerTensLabel0"
        "xpos"			    "c1"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "0"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerTensLabelShadow0"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerTensLabelShadow0"
        "xpos"			    "c1"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "0"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerTensLabel1"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerTensLabel1"
        "xpos"			    "c1"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "1"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerTensLabelShadow1"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerTensLabelShadow1"
        "xpos"			    "c1"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "1"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerTensLabel2"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerTensLabel2"
        "xpos"			    "c1"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "2"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerTensLabelShadow2"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerTensLabelShadow2"
        "xpos"			    "c1"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "2"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerTensLabel3"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerTensLabel3"
        "xpos"			    "c1"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "3"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerTensLabelShadow3"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerTensLabelShadow3"
        "xpos"			    "c1"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "3"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerTensLabel4"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerTensLabel4"
        "xpos"			    "c1"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "4"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerTensLabelShadow4"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerTensLabelShadow4"
        "xpos"			    "c1"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "4"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerTensLabel5"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerTensLabel5"
        "xpos"			    "c1"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "5"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerTensLabelShadow5"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerTensLabelShadow5"
        "xpos"			    "c1"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "5"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }
}
