"Resource/UI/persistent_timer/persistent_timer_ones.res"
{
    "PersistentTimerOnesLabel0"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabel0"
        "xpos"			    "c8"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "0"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerOnesLabelShadow0"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabelShadow0"
        "xpos"			    "c8"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "0"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerOnesLabel1"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabel1"
        "xpos"			    "c8"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "1"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerOnesLabelShadow1"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabelShadow1"
        "xpos"			    "c8"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "1"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerOnesLabel2"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabel2"
        "xpos"			    "c8"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "2"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerOnesLabelShadow2"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabelShadow2"
        "xpos"			    "c8"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "2"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerOnesLabel3"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabel3"
        "xpos"			    "c8"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "3"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerOnesLabelShadow3"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabelShadow3"
        "xpos"			    "c8"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "3"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerOnesLabel4"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabel4"
        "xpos"			    "c8"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "4"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerOnesLabelShadow4"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabelShadow4"
        "xpos"			    "c8"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "4"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerOnesLabel5"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabel5"
        "xpos"			    "c8"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "5"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerOnesLabelShadow5"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabelShadow5"
        "xpos"			    "c8"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "5"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerOnesLabel6"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabel6"
        "xpos"			    "c8"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "6"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerOnesLabelShadow6"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabelShadow6"
        "xpos"			    "c8"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "6"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerOnesLabel7"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabel7"
        "xpos"			    "c8"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "7"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerOnesLabelShadow7"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabelShadow7"
        "xpos"			    "c8"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "7"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerOnesLabel8"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabel8"
        "xpos"			    "c8"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "8"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerOnesLabelShadow8"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabelShadow8"
        "xpos"			    "c8"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "8"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }

    "PersistentTimerOnesLabel9"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabel9"
        "xpos"			    "c8"
        "ypos"			    "c55"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "9"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "White"
    }

    "PersistentTimerOnesLabelShadow9"
    {
        "ControlName"	    "CExLabel"
        "fieldName"		    "PersistentTimerOnesLabelShadow9"
        "xpos"			    "c8"
        "ypos"			    "c56"
        "zpos"			    "5"
        "wide"			    "10"
        "tall"			    "10"
        "visible"		    "0"
        "enabled"		    "1"
        "labelText"		    "9"
        "textAlignment"		"center"
        "dulltext"		    "0"
        "brighttext"		"0"
        "wrap"			    "0"
        "font"			    "HudFontSmall"
        "fgcolor"           "Black"
    }
}
